meta_product_name: "Whats In?"
meta_title: "Whats In? - Let's make eating fun again!"
meta_description: "Let's make eating fun again for people with food restrictions or allergies!"
meta_image: "cover_landscape.png" # should exist in `app/assets/images/`
twitter_account: "@whatsin_twitter_account"   # required for Twitter Cards
