meta_product_name: "Whats In?"
meta_title: "Whats In? - Let's make eating fun again!"
meta_description: "The freedom of eating out with friends for people with food restrictions"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@whatsin_twitter_account"   # required for Twitter Cards
